# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled-gridver.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setMaximumSize(QtCore.QSize(230, 200))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 17, 16))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.groupBox_7)
        self.label.setGeometry(QtCore.QRect(10, 40, 55, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 76, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 46, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 46, 16))
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 50, 16))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 70, 16))
        self.label_7.setObjectName("label_7")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton.setGeometry(QtCore.QRect(110, 20, 45, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_2.setGeometry(QtCore.QRect(160, 20, 68, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMaximumSize(QtCore.QSize(210, 149))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMaximumSize(QtCore.QSize(210, 113))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya_Ekle = QtWidgets.QMenu(self.menubar)
        self.menuDosya_Ekle.setObjectName("menuDosya_Ekle")
        self.menuUzla_t_rmac = QtWidgets.QMenu(self.menubar)
        self.menuUzla_t_rmac.setObjectName("menuUzla_t_rmac")
        self.menu_ablonlar = QtWidgets.QMenu(self.menubar)
        self.menu_ablonlar.setObjectName("menu_ablonlar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDosya_Ekle = QtWidgets.QAction(MainWindow)
        self.actionDosya_Ekle.setObjectName("actionDosya_Ekle")
        self.actionDosya_Sil = QtWidgets.QAction(MainWindow)
        self.actionDosya_Sil.setObjectName("actionDosya_Sil")
        self.actionUzla_t_rmac_Ekle = QtWidgets.QAction(MainWindow)
        self.actionUzla_t_rmac_Ekle.setObjectName("actionUzla_t_rmac_Ekle")
        self.actionUzla_t_rmac_Sil = QtWidgets.QAction(MainWindow)
        self.actionUzla_t_rmac_Sil.setObjectName("actionUzla_t_rmac_Sil")
        self.action_ablon_Ekle = QtWidgets.QAction(MainWindow)
        self.action_ablon_Ekle.setObjectName("action_ablon_Ekle")
        self.action_ablon_D_zenle = QtWidgets.QAction(MainWindow)
        self.action_ablon_D_zenle.setObjectName("action_ablon_D_zenle")
        self.action_ablon_Sil = QtWidgets.QAction(MainWindow)
        self.action_ablon_Sil.setObjectName("action_ablon_Sil")
        self.menuDosya_Ekle.addAction(self.actionDosya_Ekle)
        self.menuDosya_Ekle.addAction(self.actionDosya_Sil)
        self.menuUzla_t_rmac.addAction(self.actionUzla_t_rmac_Ekle)
        self.menuUzla_t_rmac.addAction(self.actionUzla_t_rmac_Sil)
        self.menu_ablonlar.addAction(self.action_ablon_Ekle)
        self.menu_ablonlar.addAction(self.action_ablon_D_zenle)
        self.menu_ablonlar.addAction(self.action_ablon_Sil)
        self.menubar.addAction(self.menuDosya_Ekle.menuAction())
        self.menubar.addAction(self.menuUzla_t_rmac.menuAction())
        self.menubar.addAction(self.menu_ablonlar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Dosya Bilgileri"))
        self.label_4.setText(_translate("MainWindow", "Suç"))
        self.label.setText(_translate("MainWindow", "Uzlaşma No"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Dosya Seç"))
        self.label_5.setText(_translate("MainWindow", "Suç Tarihi"))
        self.label_6.setText(_translate("MainWindow", "Dosya No"))
        self.label_2.setText(_translate("MainWindow", "Soruşturma No"))
        self.label_3.setText(_translate("MainWindow", "M.Esas No"))
        self.label_7.setText(_translate("MainWindow", "Dosya Durumu"))
        self.radioButton.setText(_translate("MainWindow", "Aktif"))
        self.radioButton_2.setText(_translate("MainWindow", "Kapanmış"))
        self.groupBox.setTitle(_translate("MainWindow", "Uzlaştırmacı"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Dosya Durumu"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_4.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dosya Bilgileri"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuDosya_Ekle.setTitle(_translate("MainWindow", "Dosya"))
        self.menuUzla_t_rmac.setTitle(_translate("MainWindow", "Uzlaştırmacı"))
        self.menu_ablonlar.setTitle(_translate("MainWindow", "Şablonlar"))
        self.actionDosya_Ekle.setText(_translate("MainWindow", "Dosya Ekle"))
        self.actionDosya_Sil.setText(_translate("MainWindow", "Dosya Sil"))
        self.actionUzla_t_rmac_Ekle.setText(_translate("MainWindow", "Uzlaştırmacı Ekle"))
        self.actionUzla_t_rmac_Sil.setText(_translate("MainWindow", "Uzlaştırmacı Sil"))
        self.action_ablon_Ekle.setText(_translate("MainWindow", "Şablon Ekle"))
        self.action_ablon_D_zenle.setText(_translate("MainWindow", "Şablon Düzenle"))
        self.action_ablon_Sil.setText(_translate("MainWindow", "Şablon Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

