# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarafekle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TarafEkle(object):
    def setupUi(self, TarafEkle):
        TarafEkle.setObjectName("TarafEkle")
        TarafEkle.resize(570, 479)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lib/icon/stock_people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TarafEkle.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(TarafEkle)
        self.label.setGeometry(QtCore.QRect(10, 10, 90, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit.setGeometry(QtCore.QRect(80, 10, 182, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(TarafEkle)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 90, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(TarafEkle)
        self.comboBox.setGeometry(QtCore.QRect(80, 40, 182, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(TarafEkle)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 90, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 70, 182, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(TarafEkle)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 90, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 100, 182, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(TarafEkle)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 90, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 130, 182, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 160, 182, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(TarafEkle)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 90, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(TarafEkle)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 90, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_6.setGeometry(QtCore.QRect(80, 190, 182, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(TarafEkle)
        self.lineEdit_7.setGeometry(QtCore.QRect(80, 250, 182, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(TarafEkle)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 90, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(TarafEkle)
        self.label_9.setGeometry(QtCore.QRect(10, 280, 90, 20))
        self.label_9.setObjectName("label_9")
        self.textEdit = QtWidgets.QTextEdit(TarafEkle)
        self.textEdit.setGeometry(QtCore.QRect(80, 280, 181, 91))
        self.textEdit.setObjectName("textEdit")
        self.label_10 = QtWidgets.QLabel(TarafEkle)
        self.label_10.setGeometry(QtCore.QRect(10, 380, 90, 20))
        self.label_10.setObjectName("label_10")
        self.radioButton = QtWidgets.QRadioButton(TarafEkle)
        self.radioButton.setGeometry(QtCore.QRect(100, 380, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(TarafEkle)
        self.radioButton_2.setGeometry(QtCore.QRect(150, 380, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(TarafEkle)
        self.pushButton.setGeometry(QtCore.QRect(190, 440, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_11 = QtWidgets.QLabel(TarafEkle)
        self.label_11.setGeometry(QtCore.QRect(10, 410, 90, 20))
        self.label_11.setObjectName("label_11")
        self.checkBox = QtWidgets.QCheckBox(TarafEkle)
        self.checkBox.setGeometry(QtCore.QRect(100, 410, 70, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(TarafEkle)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 410, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.line = QtWidgets.QFrame(TarafEkle)
        self.line.setGeometry(QtCore.QRect(270, 0, 16, 441))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget = QtWidgets.QWidget(TarafEkle)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(280, 10, 281, 431))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setEnabled(False)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 271, 171))
        self.groupBox.setObjectName("groupBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 20, 90, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 20, 182, 20))
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 50, 182, 20))
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 90, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 80, 182, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 80, 90, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 90, 20))
        self.label_16.setObjectName("label_16")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 110, 182, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 190, 271, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 90, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(70, 20, 182, 20))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(70, 50, 182, 20))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 90, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 80, 90, 20))
        self.label_19.setObjectName("label_19")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_3.setGeometry(QtCore.QRect(70, 80, 182, 71))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_12 = QtWidgets.QLabel(TarafEkle)
        self.label_12.setGeometry(QtCore.QRect(10, 220, 90, 20))
        self.label_12.setObjectName("label_12")
        self.comboBox_2 = QtWidgets.QComboBox(TarafEkle)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 220, 182, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.retranslateUi(TarafEkle)
        self.radioButton_2.clicked.connect(self.groupBox.show)
        self.checkBox_2.clicked.connect(self.groupBox_2.show)
        self.radioButton_2.clicked.connect(self.widget.show)
        self.checkBox_2.clicked.connect(self.widget.show)
        self.pushButton.clicked.connect(TarafEkle.close)
        QtCore.QMetaObject.connectSlotsByName(TarafEkle)

    def retranslateUi(self, TarafEkle):
        _translate = QtCore.QCoreApplication.translate
        TarafEkle.setWindowTitle(_translate("TarafEkle", "Taraf Ekle"))
        self.label.setText(_translate("TarafEkle", "Ad Soyad"))
        self.label_2.setText(_translate("TarafEkle", "Taraf"))
        self.comboBox.setItemText(0, _translate("TarafEkle", "Taraf Seç"))
        self.comboBox.setItemText(1, _translate("TarafEkle", "Mağdur / Katılan"))
        self.comboBox.setItemText(2, _translate("TarafEkle", "Suçtan Zarar Gören"))
        self.comboBox.setItemText(3, _translate("TarafEkle", "Şüpheli / Sanık"))
        self.comboBox.setItemText(4, _translate("TarafEkle", "Müşteki Şüpheli"))
        self.label_3.setText(_translate("TarafEkle", "TC No"))
        self.label_4.setText(_translate("TarafEkle", "Baba Adı"))
        self.label_5.setText(_translate("TarafEkle", "Anne Adı"))
        self.label_6.setText(_translate("TarafEkle", "Doğum Yeri"))
        self.label_7.setText(_translate("TarafEkle", "Doğum Tarihi"))
        self.label_8.setText(_translate("TarafEkle", "Telefon"))
        self.label_9.setText(_translate("TarafEkle", "Adres"))
        self.label_10.setText(_translate("TarafEkle", "Kanuni Temsilcisi"))
        self.radioButton.setText(_translate("TarafEkle", "Yok"))
        self.radioButton_2.setText(_translate("TarafEkle", "Var"))
        self.pushButton.setText(_translate("TarafEkle", "Ekle"))
        self.label_11.setText(_translate("TarafEkle", "Tercüman"))
        self.checkBox.setText(_translate("TarafEkle", "Yok"))
        self.checkBox_2.setText(_translate("TarafEkle", "Var"))
        self.groupBox.setTitle(_translate("TarafEkle", "Kanuni Temsilci Bilgileri"))
        self.label_13.setText(_translate("TarafEkle", "Ad Soyad"))
        self.label_14.setText(_translate("TarafEkle", "Sicil No"))
        self.label_15.setText(_translate("TarafEkle", "Telefon"))
        self.label_16.setText(_translate("TarafEkle", "Adres"))
        self.groupBox_2.setTitle(_translate("TarafEkle", "Tercüman Bilgileri"))
        self.label_17.setText(_translate("TarafEkle", "Ad Soyad"))
        self.label_18.setText(_translate("TarafEkle", "TC No"))
        self.label_19.setText(_translate("TarafEkle", "Adres"))
        self.label_12.setText(_translate("TarafEkle", "Cinsiyet"))
        self.comboBox_2.setItemText(0, _translate("TarafEkle", "Cinsiyet"))
        self.comboBox_2.setItemText(1, _translate("TarafEkle", "Kadın"))
        self.comboBox_2.setItemText(2, _translate("TarafEkle", "Erkek"))

